### PR TITLE
Ngen GUI Initial Catchment Overlay of MapView and Formulation Configuration 

### PR DESCRIPTION
**Pull request by jdmattern-noaa**
Ngen Django GUI additions initial catchment overlay of MapView and for default formulation configurations and variable selection of selected catchments.

## Additions
Adding hydro-fabric catchment data of Sugar Creek, NC domain from ngen. Updates to the Django backend python files, JavaScript, HTML, and CSS for mapping and frontend configuration of selected catchments.

## Testing

1. Django GUI additions currently tested only in Windows.

## Notes

-

## Todos
Further iteration needed to expand capability of multi-catchment selection and frontend and backend configuration.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [x] Windows
- [ ] Linux
- [x] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] No linting errors or warnings

### CODE REVIEW

**Comment by jdmattern-noaa** [comment]
@christophertubbs @hellkite500 I can't seem to request reviewers for this PR but would like to request you.

**Comment by jdmattern-noaa** [comment]
@hellkite500 Do these test failures make sense to you?

**Comment by hellkite500** [comment]
> @hellkite500 Do these test failures make sense to you?

Not really, at least at this point.  We are looking at it.

**Review by robertbartel — APPROVED** [review]
As with #60, it doesn't look like the failed checks have anything to do with the actual code changes.  Hopefully, that will get resolved once #57 is approved, which seems to have resolved the checks problem.

Regardless, this looks fine and is almost certainly independent from the problem with the checks, so I am going to go ahead and approve/merge it.

**Pull request merged**
