### PR TITLE
Fix setup.py readme and version path references

### PR DESCRIPTION
**Pull request by aaraney**
Subpackage's `setup.py` files now resolve paths to `README.md` and `_version.py` relative to the `setup.py`, instead of where `pip` or `python setup.py install` is called. Enables installing subpackages without changing the current working directory to a subpackage's root (where `setup.py` lives).

### CODE REVIEW

**Review by robertbartel — CHANGES_REQUESTED** [review]
The changes themselves look fine, but let's do this for all the packages.  Looking quickly, I think everything under _python/lib/_ is covered, but nothing under _python/services/_.

**Comment by aaraney** [comment]
@robertbartel, just made the changes to the services `setup.py`'s.

**Comment by robertbartel** [comment]
@aaraney, I'd let this one slip my mind, and now I've gone and broken it.

I just merged #244, expecting theses wouldn't conflict, but they do. Sorry about that. It looks like spacing and parentheses closing for some of the files tripped up the merging.

**Comment by aaraney** [comment]
@robertbartel, no worries. In the back of my mind while reviewing #244 I was fearful this might happen. Oh well. I'll resolve the conflicts and then we should be all set.

**Comment by aaraney** [comment]
I'd not used github's merge conflict resolution feature before, but that was pretty painless. @robertbartel, if you can give it another glance when you have a chance that would be much appreciated. Merge at will.

**Comment by robertbartel** [comment]
@aaraney, this isn't going to work.

Using a merge commit (which I am pretty sure that did) will mess up our rebasing workflow.   Don't worry,  you're in good company:  I think everyone who has done significant work on DMOD has done this via the Github interface for fixing conflicts at some point.

You should be able to re-pin to the previous commit, and after locally rebase and push.

**Comment by aaraney** [comment]
Arrr, thanks for the guidance. I'll get a new PR opened (and ref this PR) after a local rebase.

**Pull request closed without merging**
