### PR TITLE
Update gh actions unit test

### LINKED ISSUE #457: Add Python version matrix in Actions workflow to test with different versions of Python
Use a matrix with current Github Actions for automated Python tests to support testing with multiple (and hopefully all) supported versions of Python.  An example of this is set up in the [ngen-cal package's Action workflow config](https://github.com/NOAA-OWP/ngen-cal/blob/8d46c053b4a6d553d0b6e2c4ac539b5c092a2a63/.github/workflows/ngen-cal.yaml).

### PR DESCRIPTION
**Pull request by aaraney**
- Add build python matrix. Tests now run on python `3.8`, `3.9`, `3.10`, and `3.11`.
- Add step to echo dependency versions. This is useful for debugging purposes.
- Fix TLS certs email todo. Certs now use phony `dmod_gh_action@fake.gov` email address.

closes #457

### CODE REVIEW

**Comment by aaraney** [comment]
Nice! So we have failures in `3.8` because of the use of `list[str]` instead of `typing.List[str]` as a type hint. See #464 for more detail.

**Comment by aaraney** [comment]
Opened #467 to track a failure due to removal of the `ModelExecRequestClient` class.

**Comment by aaraney** [comment]
Until https://github.com/NOAA-OWP/ngen-cal/pull/64 is merged, `pandas` will need to be built in each gh action run (unless we add a cache) for `3.10` and `3.11` b.c. `ngen-cal` requires an older version of `pandas` that is not pre-built for these versions.

**Comment by aaraney** [comment]
https://github.com/NOAA-OWP/ngen-cal/pull/64 has been merged. This should be good to go now.

**Review by robertbartel — APPROVED** [review]

**Pull request merged**
