### PR TITLE
Pin pydantic<2

### PR DESCRIPTION
**Pull request by aaraney**
[Pydantic 2](https://pypi.org/project/pydantic/2.0/) was released today. This major version release introduces some breaking changes that we _may_ need to address in the future.

## Changes

- pin `pydantic>=1.10.8,~=1.10`

### CODE REVIEW

**Comment by PhilMiller** [comment]
It's generally preferable to specify a positive version constraint, like `pydantic~=1.10` ( think that's what we want here), so that it's explicit what *is* compatible rather than what isn't

**Comment by aaraney** [comment]
@PhilMiller, that's fair. Thanks for the insight. I'll searched for the minimum supported version of `pydantic` and update this PR.

**Comment by aaraney** [comment]
This is ready now.

**Review by robertbartel — APPROVED** [review]

**Comment by aaraney** [comment]
Thanks, @robertbartel!

**Pull request merged**
