### PR TITLE
Code modification to display comids for huc01 with the new crosswalk-mapping.json format

### PR DESCRIPTION
**Pull request by stcui007**
Code modification for huc01 comids display

## Additions

-

## Removals

-

## Changes

python/gui/MaaS/cbv/crosswalk.py
python/gui/MaaS/static/common/js/map.js

## Testing

Display comids in the web browser as expected.

## Notes

-

## Todos

-

## Checklist

- [x] PR has an informative and human-readable title
- [x ] Changes are limited to a single goal (no scope creep)
- [x ] Code can be automatically merged (no conflicts)
- [x ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [x ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [ ] Windows
- [ x] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] No linting errors or warnings

### CODE REVIEW

**Comment by robertbartel** [comment]
@stcui007, while the changes look fine, it looks like there is a merge conflict and they cannot be rebased automatically.  Please manually rebase things and fix the conflict, and then I'll review again.

**Comment by stcui007** [comment]
Will do.

**Comment by stcui007** [comment]
Can you check if you can merge now?

**Comment by aaraney** [comment]
Close this as stale.

**Pull request closed without merging**
