### PR TITLE
Fix django test script

### PR DESCRIPTION
**Pull request by aaraney**
I _think_ the django test script we've been using in CI has been giving us false positives. At least the tests are failing on my local machine. Just a minor improvements to how we detect success / failure.

### CODE REVIEW

**Comment by aaraney** [comment]
Moving this to draft status because only unveils the existing problem. Test reporting is still broken. I think it makes the most sense to work on this with @christophertubbs once he is back.

**Review by christophertubbs — APPROVED** [review]
This is objectively better functionality. 10/10 all around.

**Comment by aaraney** [comment]
The `evaluationservice` tests are passing now :tada:. However, the `gui` tests are still failing. Looks like [`ModelExecRequestClient`](https://github.com/NOAA-OWP/DMOD/blob/ec2396e6ae3b37ee0f2bc29c892b5119be6fa4e2/python/gui/MaaS/cbv/DMODProxy.py#L15), which no longer exists, is being imported in the `DMODProxy` module for use in the `PostFormRequestClient` class. The `EditView` module ends up importing something from `DMODProxy` and thus causes the error we are seeing in the tests:

https://github.com/NOAA-OWP/DMOD/actions/runs/8723927609/job/23933294022?pr=579#step:11:330

@robertbartel / @christophertubbs how should we remedy this?

**Review by christophertubbs — APPROVED** [review]
Good job

**Pull request merged**
