### PR TITLE
Fixes and improvements to Docker stack image builds and dependencies

### PR DESCRIPTION
**Pull request by robertbartel**
Fixes and improvements to Docker stack image builds and dependencies.

- Add Python package version constraint to `schedulerservice` and `requestservice` Docker images
- Optimizing `py-sources` Docker image build layers for fewer long rebuilds
- Default to better versions for NetCDF packags in `nwm-deps` image
- Bump model execution `base` image to be based on alpine 3.15
- Fix `base` Docker image apk package add command
- Add `pandas` to `ngen-deps` image apk packages
- Fix `nwm-deps` image build for `apk` '--repository' use
- Fix MPI build issue in `nwm-deps` in new alpine
- Fix bug in `nwm-deps` with MPI build and job count

### CODE REVIEW

**Comment by mattw-nws** [comment]
Curiously I checkout out this branch and tried `./scripts/control_stack.sh main build` and got the following error late in the build:

```
 => [stage-1 7/8] COPY ./entrypoint.sh entrypoint.sh                                                                                                                                            0.0s
 => ERROR [stage-1 8/8] RUN pip install --no-index --find-links=/DIST dmod-subsetservice     && rm -r /DIST                                                                                     3.7s
------                                                                                                                                                                                               
 > [stage-1 8/8] RUN pip install --no-index --find-links=/DIST dmod-subsetservice     && rm -r /DIST:                                                                                                
#14 0.876 Looking in links: /DIST                                                                                                                                                                    
#14 0.907 Processing /DIST/dmod_subsetservice-0.3.0-py3-none-any.whl                                                                                                                                 
#14 0.954 Processing /DIST/Flask-2.0.2-py3-none-any.whl                                                                                                                                              
#14 1.024 Processing /DIST/dmod_modeldata-0.4.0-py3-none-any.whl                                                                                                                                     
#14 1.076 Processing /DIST/Jinja2-3.0.3-py3-none-any.whl
#14 1.127 Processing /DIST/itsdangerous-2.0.1-py3-none-any.whl
#14 1.166 Processing /DIST/click-8.0.3-py3-none-any.whl
#14 1.209 Processing /DIST/Werkzeug-2.0.2-py3-none-any.whl
#14 1.268 Processing /DIST/numpy-1.22.1-cp38-cp38-linux_x86_64.whl
#14 1.617 Processing /DIST/geopandas-0.6.3-py2.py3-none-any.whl
#14 1.682 Processing /DIST/dmod_communication-0.4.1-py3-none-any.whl
#14 1.735 Processing /DIST/pandas-1.4.0-cp38-cp38-linux_x86_64.whl
#14 2.330 Collecting hypy@ git+https://github.com/noaa-owp/hypy@master#egg=hypy&subdirectory=python
#14 2.330   Cloning https://github.com/noaa-owp/hypy (to revision master) to /tmp/pip-install-0n67n9ik/hypy
#14 2.330   Running command git clone -q https://github.com/noaa-owp/hypy /tmp/pip-install-0n67n9ik/hypy
#14 3.518 ERROR: Could not find a version that satisfies the requirement MarkupSafe>=2.0 (from Jinja2>=3.0->flask->dmod-subsetservice) (from versions: none)
#14 3.518 ERROR: No matching distribution found for MarkupSafe>=2.0 (from Jinja2>=3.0->flask->dmod-subsetservice)
------
executor failed running [/bin/sh -c pip install --no-index --find-links=/DIST ${subsetservice_package_name}     && rm -r /DIST]: exit code: 1
ERROR: Service 'subset-service' failed to build : Build failed
Error: requested 'build' action failed (1); exiting without proceeding further
```

Unsure what the issue is there or why I hit it...is that the wrong thing to try? Do I need to clean something first?

**Comment by mattw-nws** [comment]
After doing `docker builder prune` and `control_stack.sh main build` again I got a similar but different error:

```
#14 4.105 ERROR: Could not find a version that satisfies the requirement websockets>=8.1 (from dmod-communication>=0.3.0->dmod-modeldata>=0.3.0->dmod-subsetservice) (from versions: none)
#14 4.105 ERROR: No matching distribution found for websockets>=8.1 (from dmod-communication>=0.3.0->dmod-modeldata>=0.3.0->dmod-subsetservice)
------
executor failed running [/bin/sh -c pip install --no-index --find-links=/DIST ${subsetservice_package_name}     && rm -r /DIST]: exit code: 1
ERROR: Service 'subset-service' failed to build : Build failed
Error: requested 'build' action failed (1); exiting without proceeding further
```

**Comment by robertbartel** [comment]
@mattw-nws I've add a workaround for that issue by installing certain packages in a separate `pip` command (but within the same Docker build layer) that uses the standard index and not just a local directory with wheels from `py-sources`.

**Comment by mattw-nws** [comment]
Okay! Now build `py-sources` and `main` with success!

**Review by mattw-nws — APPROVED** [review]

**Pull request merged**
