### PR TITLE
Refactor dmod.core using pydantic

### PR DESCRIPTION
**Pull request by aaraney**
The main goals of this PR are to improve code readability and simplify and offload type coercion and validation to `pydantic`. 

This PR refactors how the `core` package's enums and `Serializable` subtypes are serialized, deserialized, and validated. As the title suggests, the major change in this PR is the introduction of [`pydantic`](https://docs.pydantic.dev/) to handle the tasks of serialization, deserialization, and validation. 

This PR is nearly be one-to-one feature compliant.~, however there are some small changes in how dictionaries and enums are handled that could affect other portions of the code base.~ 

1. ~`to_dict` now returns all enums as enum instances.~
2. ~`to_json` always returns enums encoded using their `name` attribute.~

Prior to this PR, `to_dict`'s behavior was not consistent across subtypes of `Serializable`. Generally enums would be returned using an instance of an enum type, but in other cases the enum's `name` attribute was returned as a `str`. This will cause issues if you try to `json.dumps` a dictionary with an enum instance that does not take a secondary subtype of `int` or `str` (i.e. `StrEnum(str, Enum):`). This however does not affect `factory_init_from_deserialized_json`. Across all subtypes, the method is now more robust and in the case of enums, accepts either an enums `name` attribute or enum instance.

## Changes

- ~`Serializable` subtypes `to_dict` now returns all enums as enum instances.~
- ~`Serializable` subtypes `to_json` always returns enums encoded using their `name` attribute.~

## Testing

1. `meta_data` module unittests added
2. `dataset` unittests added. more json deserialization tests should be added in the future.

## Todos

- [ ] bump `dmod.core` version prior to merge.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by aaraney** [comment]
Im not entirely happy with the implications of `to_dict`'s handling of `enums`. I would rather it always return a serializable form of an enum rather than an instance of the enum itself. Thoughts on that @robertbartel?

**Comment by robertbartel** [comment]
@aaraney, my first reaction is that I am also uneasy about how `to_dict` would handle enums.  I would prefer it convert them to something serialized, probably the name string.  

In fact, that seems to have been my original intent:   the type hinting and docstring in the abstract declaration of `Serializable.to_dict` imply enums would be represented as a string.  So, I would have expected "proper" implementations should have returned the `name` for the enum value.   

I am curious where you found examples of `to_dict` handling enums as enum objects (starting to look at changes, but haven't found it on my own yet).  I could have just messed up when adding some new types, but if I deliberately deviated from the previous design, my motivates could have implications here.

**Comment by aaraney** [comment]
> I am curious where you found examples of `to_dict` handling enums as enum objects (starting to look at changes, but haven't found it on my own yet). I could have just messed up when adding some new types, but if I deliberately deviated from the previous design, my motivates could have implications here.

I may have been blowing smoke, I can't find an instance of it either. My apologies.

Just as a word of caution, as i'm refactoring the `communication` package, I am wishing I would've done several things differently in this PR. So much so, that I think I am going to mark this as draft and rework this as a new PR. However, the main idea of this PR and the subsequent PR will be the same. Moreover, I think this PR serves as a good introduction for those who read / review it to pydantic and it's functionality.

**Comment by robertbartel** [comment]
> I may have been blowing smoke, I can't find an instance of it either. My apologies.

I pretty sure there are `factory_init_from_deserialized_json` and/or `__init__` implementations that accept either the name string or the enum value for something like this.  That may have been where you got it from.  Though I won't be surprised if we eventually do find one.

> This PR is nearly be one-to-one feature compliant, however there are some small changes in how dictionaries and enums are handled that could affect other portions of the code base.
> 
> 1. to_dict now returns all enums as enum instances.
> 2. to_json always returns enums encoded using their name attribute.

If we strike number 1 here, then I think by implication number 2 already functioned in that manner, though correct me if I am wrong.  Regardless, does that mean this is now _fully_ one-to-one feature compliant?

**Comment by aaraney** [comment]
> I'm pretty sure there are `factory_init_from_deserialized_json` and/or `__init__` implementations that accept either the name string or the enum value for something like this. That may have been where you got it from. Though I won't be surprised if we eventually do find one.

👍🏻 



> If we strike number 1 here, then I think by implication number 2 already functioned in that manner, though correct me if I am wrong. Regardless, does that mean this is now _fully_ one-to-one feature compliant?

You are correct. I've now fully corrected the PR description. This PR in it's current form, no, (ive not altered the enum behavior in this branch) but the subsequent PR will be one-to-one compliant.

**Comment by aaraney** [comment]
#239 is the rework of this draft. As such, I am closing this PR.

**Pull request closed without merging**
