### PR TITLE
Generalize launcher

### PR DESCRIPTION
**Pull request by hellkite500**
[Short description explaining the high-level reason for the pull request]

## Additions

- add `domain` property to request

## Removals

-

## Changes

- refactor `image_and_domain.yml` file for better support of multiple models
- expose `version` as an instance property instead of `@classmethod`
- set service name based on job model name
- change NWM model name to lowercase nwm
- initialize all `JobImpl` objects with a random uuid using `uuid.uuid4()`

## Testing

1. Existing tests pass, start_job tested with ngen and nwm

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Other

- [ ] No linting errors or warnings

### CODE REVIEW

**Comment by hellkite500** [comment]
Do not merge! Working on fixing tests.

**Comment by hellkite500** [comment]
Updated some of the existing tests, but still won't pass all new tests in CI until #46 is added as well.

**Comment by stcui007** [comment]
I'll review it.

**Review by robertbartel — CHANGES_REQUESTED** [review]
I mentioned it there, but I'll note here too that the _scheduler_ package will need its dependency for _communications_ bumped to whatever the version is after #46, and then to have its own version incremented.  

Beyond that, I think this is good for the most part, but since things are a little more intricate, I'd like to see the changes from #46 incorporated after that one is merged upstream and then make sure the tests pass.

**Comment by hellkite500** [comment]
Testing all passes locally on two independent environments, CI testing here failing due to #49 .

**Review by robertbartel — APPROVED** [review]

**Pull request merged**
